### ISSUE TITLE
Feature Request: Keybinding tiles

### ISSUE THREAD

**Issue by Hatler113** [roukaour/polished-map#4]
I think it would be awesome to be able to keybind tiles as it would save lots of time.

when i select a tile in the bar on the left and press a control + number key it should get bound to said number, so that i can quick acces up to 10 different tiles.

A really nice addition to that would be if you were able to quickly flick through the different tiles by scrolling the mousewheel. As you can see in the picture below there should be a bar at the bottom of the editor showing which tile is bound to which key and you should see the currently selected one with the same indicator as on the left bar.

![screenshot with added quick access bar](https://s1.postimg.org/7opiel3uct/Keybinding_tiles.png)

thank you for your time and for creating this neat map editor.

**Comment by roukaour** [comment]
Interesting idea! I'll see what I can do.

**Comment by roukaour** [comment]
Version 2.1.4 uses Ctrl+0-9 to assign a hotkey, 0-9 to select, Ctrl+Shift+0-9 to unassign. There's no visible mini-palette of hotkeyed blocks, but they do have their hotkeys printed in red in the top-right. I might get around to doing a scrollable palette.
