### ISSUE TITLE
Bug report: Weird saving error

### ISSUE THREAD

**Issue by Hatler113** [roukaour/polished-map#5]
I had a really weird error where i am not sure what has happened.

2 days ago i created a map that i saved as "Lighthouse.blk".

Yesterday i did some minor edits to said file and saved it as "Axylla_Lighthouse_22x12_JOHTO1.blk" to have the projectname, filesize and tileset displayed in the filename. The editor said that it had saved the map succesfully and it also displayed the new name in the top bar of the program.

Then i went ahead and opened another map (Route44 from the vanilla crystal) in a second instance of the program as i wanted to build a map that should properly connect to the lighthouse map and i wanted to use route 44 as a base for that map. i then went ahead and resized the map - did the actual mapping and then saved it as "Axylla_Route25_24x16_JOHTO1.blk" - again it said that it had saved the map succesfully and displayed the new name in the top bar of the program. I also exported both maps as PNGs which worked just fine.

I then opened the folder where i saved the files to and could only find "Lighthouse.blk" i then went ahead and saved both maps multiple times to the project folder and to other newly created empty folders. The new folders were still empty and the project folder still only had the normal vanilla pokecrystal maps + Lighthouse.
Then i thought well maybe the files will appear after closing the editor - nope.
Then i opened Lighthouse.blk and it was the initial version, before the minor touchup that i did.
There was still no other new file and Route44.blk was also still in the vanilla state.

After restarting the computer there was still no change in the above situation so i descided to fuck all that and try to figure out what the problem is or remap my stuff today.
As in today when i opened up the project folder besides the vanilla crystal maps i also found "Lighthouse.blk" and a file called "Axylla_Route25.blk" (i'm 95% sure that i never saved a map named like that), when i opened them it turned out that they are what were supposed to be "Axylla_Lighthouse_22x12_JOHTO1.blk" and "Axylla_Route25_24x16_JOHTO1.blk", while route 44 was still in its vanilla state. The non-project folders that i created are still empty though.

So yeah i really don't know what the fuck has happened here and i just hope that this was a one time problem and that this was just a weird windows error. However i thought that i should let you know of this and if something like this ever occurs again i will let you know immediately.

cheers

**Comment by roukaour** [comment]
I'm sorry you lost your work. However, I can't reproduce this problem.

I tried double-clicking OlivineLighthouse1F.blk to open it, then made some edits, went to File→Save As…, and saved it as Axylla_Lighthouse_22x12_JOHTO1.blk (in the same folder). Then I made some more edits and just did File→Save. "Save As" correctly created the file, and "Save" correctly wrote the additional changes. OlivineLighthouse1F.blk was unaffected and Axylla_Lighthouse_22x12_JOHTO1.blk had all the new changes when I closed the program and double-clicked it.

Could this be a operating system issue? Does your account and the polishedmap.exe program have permission to create new files in that directory?

To avoid further issues, I'd suggest not using Save As. Just copy+paste a .blk in Explorer, edit it., and do any file renaming in Explorer as well.

I'll keep an eye out for possible causes of this bug.

**Comment by Hatler113** [comment]
That's basically what I'm doing right now, and i'm pretty sure it has the proper rights it needs as it is able to create new files in the folder when i create a new map i can save it as NewMap.blk, just the 'Save As' button doesn't do what it is supposed to do, but the workaround using explorer to rename stuff works for now. I'll let you know if i happen to find out what causes my problem
