### ISSUE TITLE
Install instructions need to account for lib/bin/fltk-config

### ISSUE THREAD

**Issue by yenatch** [roukaour/polished-map#6]
The makefile invokes `fltk-config`, which is not in the user's path.

**Comment by roukaour** [comment]
`make install` for FLTK 1.3.4 should have put it in your path.

**Comment by mid-kid** [comment]
The installation instructions explicitly modify the user's path to do this. If you close your session and open a new one, you're going to have to run `export` again, before `make`.
If you install fltk through your package manager or don't pass the `--prefix` option to fltk's configure, it'll be installed system-wide, in which case it'll be in your path automatically.

**Comment by yenatch** [comment]
I actually missed this line somehow.
```sh
export PATH="$PWD/lib/bin:$PATH"
```
Still, if this has to be done each session it should at least be mentioned.
